### ISSUE TITLE
ReducerProtocol migration

### ISSUE THREAD

**Issue by musicdev20** [pitt500/OnlineStoreTCA#2]
This is an outstanding example!  Thank you for doing this.  I was curious if you were going to update your sample to include the new ReducerProtocol changes introduced?

**Comment by pitt500** [comment]
Hi @musicdev20,

Thanks for your comment, Absolutely! The idea is to start from the previous version to keep the legacy code available too (not everyone would be available to migrate right away).

For sure I will end the explanation of my demo with a couple of more videos and then move on to ReduceProtocol. Stay tuned!
