### ISSUE TITLE
Test failing from latest changes in main

### ISSUE THREAD

**Issue by danstorre** [pitt500/OnlineStoreTCA#4]
Description: 
Run the test from OnlineStoreTCA scheme using the latest commit of main branch.

commit: 
e77b8778742e079a9cab3c47de98c410f124eb4b

Expected:
Tests should pass.

**Comment by pitt500** [comment]
I will take a look later today. Thanks for reporting!

**Comment by pitt500** [comment]
Fixed! Thanks a lot @danstorre 🙌🏻
